spring.application.name=taskapp
spring.jpa.open-in-view=false

logging.level.org.springdoc=ERROR
logging.file.name=logs/app.log

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=never
management.info.env.enabled=true

info.app.name=Task API
info.app.version=@project.version@

server.port=${PORT:8080}