spring.application.name=taskapp
spring.jpa.open-in-view=false

logging.level.org.springdoc=ERROR
logging.file.name=logs/app.log

management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=always

server.port=${PORT:8080}