name: Deploy

on:
  push:
    branches:
      - main
      - develop

jobs:
  deploy-staging:
    if: github.ref == 'refs/heads/develop'
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Render Deploy (staging)
        run: curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK_STAGING }}

  deploy-production:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Render Deploy (production)
        run: curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK_PRODUCTION }}